apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sinatra-backend-pg-pvc
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: sinatra-backend
      type: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi