---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sinatra-backend-secret
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCxIQtRhRW3EOlBPTD2/kig0SFFl5Vu4el2daXvmrxte3lHuKXsen1OW3P+ErM5R47SQdbhzZKSQUxrkytIW7AhK4M0XYAsnUuASyGEPWzAmt6uHWXDIiVaVhJYalo5Y/gw/nPS1zMBwWQ9+hbXm0xIVGU5U6yVDJeVaGc+xkxLU98EK4ZGmMMZoLPkkk++ppTHekmwQsoE4iKghul/+igLKXtF9LCJp/ORLW2bdTJj+OqSwLMcQB3ES5wPX5t7ApvPKZCs9vfSKrsZ5w8KKM7xZ7qIxUUlDwJaq4v6H83LBbQDqKY3aD7WoQy71SjMdNgpzPlBkIyX7FZ4DUR1dWRjzDn7hbU07ax9t85lTLfyr3G3neYtEzw3sV24tXUtIm9l43xCD+YnvYk+O/GYVasrlib9puL/eZfGT5n0pFBPx0eoxmlKhGASE0zHYURpTOjRU/nnXJJ2PLwf8RQwD8+RoAPXBZCUEj/CD5FQSCW/UkyHePrpr50FuBnNedaKmtKIg1LE4CSGkQNHgc2sWSUBYQmhTpIymCFDlzMppHNXyovmDH0DSygGxtUzdDzU7K6Zx98/uccmYwTC48PunUru+eVBoXKWm5tbKRk1JF7/u1uYA6dvlWJUOrWdnRpDtpoRJGnj7GfXuqY5d6bd1xhTrZTBu+9FTuz8azv5vHy8wGttPRO1TQsfl0m1bTSBgh4blYSWfkhT7EFFO6dnf9URUY2w/oU=
  template:
    metadata:
      name: sinatra-backend-secret
      namespace: default
