---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sinatra-backend-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCQ96EGe8eze5YxDpGfjx+Xpw2INVipAsKvArCmwvB81ueMnd1HqOxkx1Hhks87sUlQ9ns/xBFLCmJeoE7Jd+IHoEy9kOeuCi37z/uQdP0YbPEyjqyzO/zYbnkAvOn0z2/Op9RC8OPWWNeJ73ERbkAyUgFXNajyPOwh1m8Ev4Yh7rrfPkqni/rFus8es/yHXMT8+O3Jein2RQ0OgYhNgjjep/hGH1edzkviqHVgDe8t/IFYhsankGgHuMauZgNt9nx6tgLhfRNnG1/49ANvj83LlvIBBWwBAm297pylfQzomUlUoJmk9cWWz2MuTW09fzgSewewQdtnyDPhd/O/65doSZPoEHkAJguTDvGYaVIn97AFqhEzPT6mUhAbiPMDlN/SGAHB4MwX3ggYqc2abLCQGqX1ihJXVnKObf53e9LrZ6qJ/NlsqxbXh2sdyKKJtevFe165o+VurlJ7W6TVS2gb+UBWxSgzE9aPFSThjaOwSokSbTJMfdg1sC66Jc6Zf3vGyue6g3MgRXMKN5DuoPRhSxXflaxHxnwf9J574M5oYR/hZVrZ6KAng/MIFVJqMEYPQ/rBbD/dMXQVe6qIJDpNRBlWaN1BzDXjj5Acj7ACj8XvdAYnOrp4oWqSIJOWsaZUMWfsVX44InPjRl9jtFE8UrlnuaqxeLvOxk/e6PhbxNpoOWl1jwSPZuhqLEzmLQ681Qo2tmOFRqGBVP7m44WUNcXTDw0=
    POSTGRES_PASSWORD: AgCQ96EGe8eze5YxDpGfjx+Xpw2INVipAsKvArCmwvB81ueMnd1HqOxkx1Hhks87sUlQ9ns/xBFLCmJeoE7Jd+IHoEy9kOeuCi37z/uQdP0YbPEyjqyzO/zYbnkAvOn0z2/Op9RC8OPWWNeJ73ERbkAyUgFXNajyPOwh1m8Ev4Yh7rrfPkqni/rFus8es/yHXMT8+O3Jein2RQ0OgYhNgjjep/hGH1edzkviqHVgDe8t/IFYhsankGgHuMauZgNt9nx6tgLhfRNnG1/49ANvj83LlvIBBWwBAm297pylfQzomUlUoJmk9cWWz2MuTW09fzgSewewQdtnyDPhd/O/65doSZPoEHkAJguTDvGYaVIn97AFqhEzPT6mUhAbiPMDlN/SGAHB4MwX3ggYqc2abLCQGqX1ihJXVnKObf53e9LrZ6qJ/NlsqxbXh2sdyKKJtevFe165o+VurlJ7W6TVS2gb+UBWxSgzE9aPFSThjaOwSokSbTJMfdg1sC66Jc6Zf3vGyue6g3MgRXMKN5DuoPRhSxXflaxHxnwf9J574M5oYR/hZVrZ6KAng/MIFVJqMEYPQ/rBbD/dMXQVe6qIJDpNRBlWaN1BzDXjj5Acj7ACj8XvdAYnOrp4oWqSIJOWsaZUMWfsVX44InPjRl9jtFE8UrlnuaqxeLvOxk/e6PhbxNpoOWl1jwSPZuhqLEzmLQ681Qo2tmOFRqGBVP7m44WUNcXTDw0=
  template:
    metadata:
      name: sinatra-backend-secret
      namespace: default
